// Copyright 2021-2022, University of Colorado Boulder

/**
 * Auto-generated from modulify, DO NOT manually modify.
 */
/* eslint-disable */
import getStringModule from '../../chipper/js/getStringModule.js';
import TReadOnlyProperty from '../../axon/js/TReadOnlyProperty.js';
import fourierMakingWaves from './fourierMakingWaves.js';

type StringsType = {
  'fourier-making-waves': {
    'title': string;
    'titleStringProperty': TReadOnlyProperty<string>;
  };
  'screen': {
    'discrete': string;
    'discreteStringProperty': TReadOnlyProperty<string>;
    'waveGame': string;
    'waveGameStringProperty': TReadOnlyProperty<string>;
    'wavePacket': string;
    'wavePacketStringProperty': TReadOnlyProperty<string>;
  };
  'fourierSeries': string;
  'fourierSeriesStringProperty': TReadOnlyProperty<string>;
  'graphControls': string;
  'graphControlsStringProperty': TReadOnlyProperty<string>;
  'measurementTools': string;
  'measurementToolsStringProperty': TReadOnlyProperty<string>;
  'sinusoid': string;
  'sinusoidStringProperty': TReadOnlyProperty<string>;
  'triangle': string;
  'triangleStringProperty': TReadOnlyProperty<string>;
  'square': string;
  'squareStringProperty': TReadOnlyProperty<string>;
  'sawtooth': string;
  'sawtoothStringProperty': TReadOnlyProperty<string>;
  'wavePacket': string;
  'wavePacketStringProperty': TReadOnlyProperty<string>;
  'custom': string;
  'customStringProperty': TReadOnlyProperty<string>;
  'waveform': string;
  'waveformStringProperty': TReadOnlyProperty<string>;
  'harmonics': string;
  'harmonicsStringProperty': TReadOnlyProperty<string>;
  'harmonicsChart': string;
  'harmonicsChartStringProperty': TReadOnlyProperty<string>;
  'functionOf': string;
  'functionOfStringProperty': TReadOnlyProperty<string>;
  'series': string;
  'seriesStringProperty': TReadOnlyProperty<string>;
  'spaceSymbol': string;
  'spaceSymbolStringProperty': TReadOnlyProperty<string>;
  'timeSymbol': string;
  'timeSymbolStringProperty': TReadOnlyProperty<string>;
  'spaceAndTimeSymbols': string;
  'spaceAndTimeSymbolsStringProperty': TReadOnlyProperty<string>;
  'wavelength': string;
  'wavelengthStringProperty': TReadOnlyProperty<string>;
  'period': string;
  'periodStringProperty': TReadOnlyProperty<string>;
  'equation': string;
  'equationStringProperty': TReadOnlyProperty<string>;
  'hidden': string;
  'hiddenStringProperty': TReadOnlyProperty<string>;
  'symbolAndSymbol': string;
  'symbolAndSymbolStringProperty': TReadOnlyProperty<string>;
  'amplitude': string;
  'amplitudeStringProperty': TReadOnlyProperty<string>;
  'sum': string;
  'sumStringProperty': TReadOnlyProperty<string>;
  'infiniteHarmonics': string;
  'infiniteHarmonicsStringProperty': TReadOnlyProperty<string>;
  'minToMax': string;
  'minToMaxStringProperty': TReadOnlyProperty<string>;
  'enter': string;
  'enterStringProperty': TReadOnlyProperty<string>;
  'sawtoothWithCosines': string;
  'sawtoothWithCosinesStringProperty': TReadOnlyProperty<string>;
  'expandedForm': string;
  'expandedFormStringProperty': TReadOnlyProperty<string>;
  'symbol': {
    'A': string;
    'AStringProperty': TReadOnlyProperty<string>;
    'cos': string;
    'cosStringProperty': TReadOnlyProperty<string>;
    'd': string;
    'dStringProperty': TReadOnlyProperty<string>;
    'F': string;
    'FStringProperty': TReadOnlyProperty<string>;
    'L': string;
    'LStringProperty': TReadOnlyProperty<string>;
    'T': string;
    'TStringProperty': TReadOnlyProperty<string>;
    'f': string;
    'fStringProperty': TReadOnlyProperty<string>;
    'k': string;
    'kStringProperty': TReadOnlyProperty<string>;
    'lambda': string;
    'lambdaStringProperty': TReadOnlyProperty<string>;
    'n': string;
    'nStringProperty': TReadOnlyProperty<string>;
    'omega': string;
    'omegaStringProperty': TReadOnlyProperty<string>;
    'sigma': string;
    'sigmaStringProperty': TReadOnlyProperty<string>;
    'sin': string;
    'sinStringProperty': TReadOnlyProperty<string>;
    't': string;
    'tStringProperty': TReadOnlyProperty<string>;
    'x': string;
    'xStringProperty': TReadOnlyProperty<string>;
  };
  'symbolsDialog': {
    'title': string;
    'titleStringProperty': TReadOnlyProperty<string>;
    'A': string;
    'AStringProperty': TReadOnlyProperty<string>;
    'f': string;
    'fStringProperty': TReadOnlyProperty<string>;
    'lambda': string;
    'lambdaStringProperty': TReadOnlyProperty<string>;
    'k': string;
    'kStringProperty': TReadOnlyProperty<string>;
    'L': string;
    'LStringProperty': TReadOnlyProperty<string>;
    'n': string;
    'nStringProperty': TReadOnlyProperty<string>;
    't': string;
    'tStringProperty': TReadOnlyProperty<string>;
    'T': string;
    'TStringProperty': TReadOnlyProperty<string>;
    'x': string;
    'xStringProperty': TReadOnlyProperty<string>;
    'sigma': string;
    'sigmaStringProperty': TReadOnlyProperty<string>;
    'omega': string;
    'omegaStringProperty': TReadOnlyProperty<string>;
  };
  'levels': string;
  'levelsStringProperty': TReadOnlyProperty<string>;
  'chooseYourLevel': string;
  'chooseYourLevelStringProperty': TReadOnlyProperty<string>;
  'matchUsing1Harmonic': string;
  'matchUsing1HarmonicStringProperty': TReadOnlyProperty<string>;
  'matchUsingNHarmonics': string;
  'matchUsingNHarmonicsStringProperty': TReadOnlyProperty<string>;
  'matchUsingNOrMoreHarmonics': string;
  'matchUsingNOrMoreHarmonicsStringProperty': TReadOnlyProperty<string>;
  'info1Harmonic': string;
  'info1HarmonicStringProperty': TReadOnlyProperty<string>;
  'infoNHarmonics': string;
  'infoNHarmonicsStringProperty': TReadOnlyProperty<string>;
  'infoNOrMoreHarmonics': string;
  'infoNOrMoreHarmonicsStringProperty': TReadOnlyProperty<string>;
  'checkAnswer': string;
  'checkAnswerStringProperty': TReadOnlyProperty<string>;
  'showAnswer': string;
  'showAnswerStringProperty': TReadOnlyProperty<string>;
  'newWaveform': string;
  'newWaveformStringProperty': TReadOnlyProperty<string>;
  'amplitudeControls': string;
  'amplitudeControlsStringProperty': TReadOnlyProperty<string>;
  'componentSpacing': string;
  'componentSpacingStringProperty': TReadOnlyProperty<string>;
  'wavePacketCenter': string;
  'wavePacketCenterStringProperty': TReadOnlyProperty<string>;
  'wavePacketWidth': string;
  'wavePacketWidthStringProperty': TReadOnlyProperty<string>;
  'amplitudesOfFourierComponents': string;
  'amplitudesOfFourierComponentsStringProperty': TReadOnlyProperty<string>;
  'fourierComponents': string;
  'fourierComponentsStringProperty': TReadOnlyProperty<string>;
  'waveformEnvelope': string;
  'waveformEnvelopeStringProperty': TReadOnlyProperty<string>;
  'widthIndicators': string;
  'widthIndicatorsStringProperty': TReadOnlyProperty<string>;
  'continuousWaveform': string;
  'continuousWaveformStringProperty': TReadOnlyProperty<string>;
  'symbolValueUnits': string;
  'symbolValueUnitsStringProperty': TReadOnlyProperty<string>;
  'symbolSymbolValueUnits': string;
  'symbolSymbolValueUnitsStringProperty': TReadOnlyProperty<string>;
  'units': {
    'meters': string;
    'metersStringProperty': TReadOnlyProperty<string>;
    'milliseconds': string;
    'millisecondsStringProperty': TReadOnlyProperty<string>;
    'radiansPerMeter': string;
    'radiansPerMeterStringProperty': TReadOnlyProperty<string>;
    'radiansPerMillisecond': string;
    'radiansPerMillisecondStringProperty': TReadOnlyProperty<string>;
  };
  'symbolUnits': string;
  'symbolUnitsStringProperty': TReadOnlyProperty<string>;
  'infiniteComponentsCannotBePlotted': string;
  'infiniteComponentsCannotBePlottedStringProperty': TReadOnlyProperty<string>;
  'keyboardHelpDialog': {
    'gameControls': string;
    'gameControlsStringProperty': TReadOnlyProperty<string>;
    'checkYourAnswer': string;
    'checkYourAnswerStringProperty': TReadOnlyProperty<string>;
    'measurementTools': string;
    'measurementToolsStringProperty': TReadOnlyProperty<string>;
    'moveTool': string;
    'moveToolStringProperty': TReadOnlyProperty<string>;
    'moveToolSlower': string;
    'moveToolSlowerStringProperty': TReadOnlyProperty<string>;
  }
};

const fourierMakingWavesStrings = getStringModule( 'FOURIER_MAKING_WAVES' ) as StringsType;

fourierMakingWaves.register( 'fourierMakingWavesStrings', fourierMakingWavesStrings );

export default fourierMakingWavesStrings;
