// Copyright 2021-2022, University of Colorado Boulder

/**
 * Auto-generated from modulify, DO NOT manually modify.
 */
/* eslint-disable */
import getStringModule from '../../chipper/js/getStringModule.js';
import LinkableProperty from '../../axon/js/LinkableProperty.js';
import fourierMakingWaves from './fourierMakingWaves.js';

type StringsType = {
  'fourier-making-waves': {
    'title': string;
    'titleStringProperty': LinkableProperty<string>;
  };
  'screen': {
    'discrete': string;
    'discreteStringProperty': LinkableProperty<string>;
    'waveGame': string;
    'waveGameStringProperty': LinkableProperty<string>;
    'wavePacket': string;
    'wavePacketStringProperty': LinkableProperty<string>;
  };
  'fourierSeries': string;
  'fourierSeriesStringProperty': LinkableProperty<string>;
  'graphControls': string;
  'graphControlsStringProperty': LinkableProperty<string>;
  'measurementTools': string;
  'measurementToolsStringProperty': LinkableProperty<string>;
  'sinusoid': string;
  'sinusoidStringProperty': LinkableProperty<string>;
  'triangle': string;
  'triangleStringProperty': LinkableProperty<string>;
  'square': string;
  'squareStringProperty': LinkableProperty<string>;
  'sawtooth': string;
  'sawtoothStringProperty': LinkableProperty<string>;
  'wavePacket': string;
  'wavePacketStringProperty': LinkableProperty<string>;
  'custom': string;
  'customStringProperty': LinkableProperty<string>;
  'waveform': string;
  'waveformStringProperty': LinkableProperty<string>;
  'harmonics': string;
  'harmonicsStringProperty': LinkableProperty<string>;
  'harmonicsChart': string;
  'harmonicsChartStringProperty': LinkableProperty<string>;
  'functionOf': string;
  'functionOfStringProperty': LinkableProperty<string>;
  'series': string;
  'seriesStringProperty': LinkableProperty<string>;
  'spaceSymbol': string;
  'spaceSymbolStringProperty': LinkableProperty<string>;
  'timeSymbol': string;
  'timeSymbolStringProperty': LinkableProperty<string>;
  'spaceAndTimeSymbols': string;
  'spaceAndTimeSymbolsStringProperty': LinkableProperty<string>;
  'wavelength': string;
  'wavelengthStringProperty': LinkableProperty<string>;
  'period': string;
  'periodStringProperty': LinkableProperty<string>;
  'equation': string;
  'equationStringProperty': LinkableProperty<string>;
  'hidden': string;
  'hiddenStringProperty': LinkableProperty<string>;
  'symbolAndSymbol': string;
  'symbolAndSymbolStringProperty': LinkableProperty<string>;
  'amplitude': string;
  'amplitudeStringProperty': LinkableProperty<string>;
  'sum': string;
  'sumStringProperty': LinkableProperty<string>;
  'infiniteHarmonics': string;
  'infiniteHarmonicsStringProperty': LinkableProperty<string>;
  'minToMax': string;
  'minToMaxStringProperty': LinkableProperty<string>;
  'enter': string;
  'enterStringProperty': LinkableProperty<string>;
  'sawtoothWithCosines': string;
  'sawtoothWithCosinesStringProperty': LinkableProperty<string>;
  'expandedForm': string;
  'expandedFormStringProperty': LinkableProperty<string>;
  'symbol': {
    'A': string;
    'AStringProperty': LinkableProperty<string>;
    'cos': string;
    'cosStringProperty': LinkableProperty<string>;
    'd': string;
    'dStringProperty': LinkableProperty<string>;
    'F': string;
    'FStringProperty': LinkableProperty<string>;
    'L': string;
    'LStringProperty': LinkableProperty<string>;
    'T': string;
    'TStringProperty': LinkableProperty<string>;
    'f': string;
    'fStringProperty': LinkableProperty<string>;
    'k': string;
    'kStringProperty': LinkableProperty<string>;
    'lambda': string;
    'lambdaStringProperty': LinkableProperty<string>;
    'n': string;
    'nStringProperty': LinkableProperty<string>;
    'omega': string;
    'omegaStringProperty': LinkableProperty<string>;
    'sigma': string;
    'sigmaStringProperty': LinkableProperty<string>;
    'sin': string;
    'sinStringProperty': LinkableProperty<string>;
    't': string;
    'tStringProperty': LinkableProperty<string>;
    'x': string;
    'xStringProperty': LinkableProperty<string>;
  };
  'symbolsDialog': {
    'title': string;
    'titleStringProperty': LinkableProperty<string>;
    'A': string;
    'AStringProperty': LinkableProperty<string>;
    'f': string;
    'fStringProperty': LinkableProperty<string>;
    'lambda': string;
    'lambdaStringProperty': LinkableProperty<string>;
    'k': string;
    'kStringProperty': LinkableProperty<string>;
    'L': string;
    'LStringProperty': LinkableProperty<string>;
    'n': string;
    'nStringProperty': LinkableProperty<string>;
    't': string;
    'tStringProperty': LinkableProperty<string>;
    'T': string;
    'TStringProperty': LinkableProperty<string>;
    'x': string;
    'xStringProperty': LinkableProperty<string>;
    'sigma': string;
    'sigmaStringProperty': LinkableProperty<string>;
    'omega': string;
    'omegaStringProperty': LinkableProperty<string>;
  };
  'levels': string;
  'levelsStringProperty': LinkableProperty<string>;
  'chooseYourLevel': string;
  'chooseYourLevelStringProperty': LinkableProperty<string>;
  'matchUsing1Harmonic': string;
  'matchUsing1HarmonicStringProperty': LinkableProperty<string>;
  'matchUsingNHarmonics': string;
  'matchUsingNHarmonicsStringProperty': LinkableProperty<string>;
  'matchUsingNOrMoreHarmonics': string;
  'matchUsingNOrMoreHarmonicsStringProperty': LinkableProperty<string>;
  'info1Harmonic': string;
  'info1HarmonicStringProperty': LinkableProperty<string>;
  'infoNHarmonics': string;
  'infoNHarmonicsStringProperty': LinkableProperty<string>;
  'infoNOrMoreHarmonics': string;
  'infoNOrMoreHarmonicsStringProperty': LinkableProperty<string>;
  'checkAnswer': string;
  'checkAnswerStringProperty': LinkableProperty<string>;
  'showAnswer': string;
  'showAnswerStringProperty': LinkableProperty<string>;
  'newWaveform': string;
  'newWaveformStringProperty': LinkableProperty<string>;
  'amplitudeControls': string;
  'amplitudeControlsStringProperty': LinkableProperty<string>;
  'componentSpacing': string;
  'componentSpacingStringProperty': LinkableProperty<string>;
  'wavePacketCenter': string;
  'wavePacketCenterStringProperty': LinkableProperty<string>;
  'wavePacketWidth': string;
  'wavePacketWidthStringProperty': LinkableProperty<string>;
  'amplitudesOfFourierComponents': string;
  'amplitudesOfFourierComponentsStringProperty': LinkableProperty<string>;
  'fourierComponents': string;
  'fourierComponentsStringProperty': LinkableProperty<string>;
  'waveformEnvelope': string;
  'waveformEnvelopeStringProperty': LinkableProperty<string>;
  'widthIndicators': string;
  'widthIndicatorsStringProperty': LinkableProperty<string>;
  'continuousWaveform': string;
  'continuousWaveformStringProperty': LinkableProperty<string>;
  'symbolValueUnits': string;
  'symbolValueUnitsStringProperty': LinkableProperty<string>;
  'symbolSymbolValueUnits': string;
  'symbolSymbolValueUnitsStringProperty': LinkableProperty<string>;
  'units': {
    'meters': string;
    'metersStringProperty': LinkableProperty<string>;
    'milliseconds': string;
    'millisecondsStringProperty': LinkableProperty<string>;
    'radiansPerMeter': string;
    'radiansPerMeterStringProperty': LinkableProperty<string>;
    'radiansPerMillisecond': string;
    'radiansPerMillisecondStringProperty': LinkableProperty<string>;
  };
  'symbolUnits': string;
  'symbolUnitsStringProperty': LinkableProperty<string>;
  'infiniteComponentsCannotBePlotted': string;
  'infiniteComponentsCannotBePlottedStringProperty': LinkableProperty<string>;
  'keyboardHelpDialog': {
    'gameControls': string;
    'gameControlsStringProperty': LinkableProperty<string>;
    'checkYourAnswer': string;
    'checkYourAnswerStringProperty': LinkableProperty<string>;
    'measurementTools': string;
    'measurementToolsStringProperty': LinkableProperty<string>;
    'moveTool': string;
    'moveToolStringProperty': LinkableProperty<string>;
    'moveToolSlower': string;
    'moveToolSlowerStringProperty': LinkableProperty<string>;
  }
};

const FourierMakingWavesStrings = getStringModule( 'FOURIER_MAKING_WAVES' ) as StringsType;

fourierMakingWaves.register( 'FourierMakingWavesStrings', FourierMakingWavesStrings );

export default FourierMakingWavesStrings;
